/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo_productos;

import DTOs.IngredienteDTO;
import DTOs.ProductoDTO;
import DTOs.ProductoIngredienteDTO;
import coordinadores.CoordinadorAplicacion;
import enums.TipoProducto;
import enums.UnidadMedida;
import excepciones.DatosInvalidosException;
import excepciones.PresentacionException;
import java.awt.BorderLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import modulo_ingredientes.BuscadorIngredientesPanel;
import validaciones.Validaciones;

/**
 *
 * @author rocha
 */
public class EditarProductoFrm extends JFrame {
    
    private CoordinadorAplicacion coordinadorAplicacion;
    
    private BuscadorIngredientesPanel buscadorPanel;
    
    private final DefaultTableModel tableModel;
    
    private ProductoDTO productoElegido;
    private List<IngredienteDTO> ingredientes; // Lista con los ingredientes seleccionados
    
    /**
     * Creates new form RegistrarProductoFrm
     */
    public EditarProductoFrm() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.WHITE);
        this.setTitle("Editar Producto");
        this.setLocationRelativeTo(null);
        this.coordinadorAplicacion = CoordinadorAplicacion.getInstancia();
        this.ingredientes = new ArrayList<>();
        this.productoElegido = new ProductoDTO();
        
        tableModel = new DefaultTableModel(new Object[]{"Ingrediente", "Unidad", "-", "Cantidad", "+"}, 0);
        tblIngredientes.setModel(tableModel);
        tblIngredientes.setDefaultEditor(Object.class, null);
        
        tblIngredientes.getColumnModel().getColumn(2).setCellRenderer(new ButtonRenderer()); // Hace que las columnas se vean como botones
        tblIngredientes.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
        tblIngredientes.getColumnModel().getColumn(2).setCellEditor(new ButtonEditor(new JCheckBox(), false)); // Botón "-"
        tblIngredientes.getColumnModel().getColumn(4).setCellEditor(new ButtonEditor(new JCheckBox(), true));  // Botón "+"
        
        insertarPanelBuscador();
        cargarListeners();
    }
    
    public void setProductoElegido(ProductoDTO producto) {
        this.productoElegido = producto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbDatosGenerales = new javax.swing.JLabel();
        lbNombreProducto = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lbPrecio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbCategoria = new javax.swing.JLabel();
        lbSeleccionarIngredientes = new javax.swing.JLabel();
        scTablaIngredientes = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        lbTablaIngredientes = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        panelBuscar = new javax.swing.JPanel();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitulo.setText("Editar Producto");

        lbDatosGenerales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDatosGenerales.setText("Datos generales");

        lbNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNombreProducto.setText("Nombre del producto");

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPrecio.setText("Precio");

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCategoria.setText("Tipo / Categoría");

        lbSeleccionarIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSeleccionarIngredientes.setText("Seleccionar ingredientes");

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingrediente", "Unidad", "-", "Cantidad", "+"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIngredientes.setRowSelectionAllowed(false);
        tblIngredientes.getTableHeader().setResizingAllowed(false);
        tblIngredientes.getTableHeader().setReorderingAllowed(false);
        scTablaIngredientes.setViewportView(tblIngredientes);

        lbTablaIngredientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTablaIngredientes.setText("Ingredientes seleccionados");

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.setBorderPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar ingrediente");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        panelBuscar.setLayout(new java.awt.BorderLayout());

        txtTipo.setEditable(false);
        txtTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(325, 325, 325))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDatosGenerales)
                    .addComponent(lbNombreProducto)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(lbPrecio)
                    .addComponent(txtNombre)
                    .addComponent(lbCategoria)
                    .addComponent(txtTipo))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnAgregar))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbSeleccionarIngredientes)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTablaIngredientes)
                    .addComponent(scTablaIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbTitulo)
                .addGap(48, 48, 48)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDatosGenerales)
                    .addComponent(lbSeleccionarIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreProducto)
                            .addComponent(lbTablaIngredientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scTablaIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        atras();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarIngredienteATabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Renderizador para el botón en la tabla (solo apariencia)
    class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true); // Hacer el botón no transparente
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString()); // Establece el texto del botón basado en el valor de la celda
            return this; // Devuelve el botón para mostrarlo en la celda de la tabla
        }
    }

    // Editor de botones para manejar incremento y decremento
    class ButtonEditor extends DefaultCellEditor {

        private JButton button;
        private boolean isIncrement; // Determina si el botón es para incrementar o decrementar
        private int row;

        public ButtonEditor(JCheckBox checkBox, boolean isIncrement) {
            super(checkBox);
            this.isIncrement = isIncrement;

            // Crear el botón con el texto adecuado para incrementar o decrementar
            this.button = new JButton(isIncrement ? "+" : "-");
            button.setOpaque(true);
            button.addActionListener(e -> manejarCantidad()); // Asocia el evento de clic al método que maneja la cantidad
        }

        // Lógica común para incrementar o decrementar la cantidad
        private void manejarCantidad() {
            int cantidad = (int) tableModel.getValueAt(row, 3);  // Obtener la cantidad de la celda correspondiente
            if (isIncrement) {
                tableModel.setValueAt(cantidad + 1, row, 3); // Incrementar la cantidad
            } else {
                if (cantidad > 1) {
                    tableModel.setValueAt(cantidad - 1, row, 3); // Decrementar la cantidad si es mayor que 1
                } else {
                    quitarIngrediente(tableModel.getValueAt(row, 0).toString(), tableModel.getValueAt(row, 1).toString());
                    tableModel.removeRow(row); // Eliminar la fila si la cantidad es 0
                    buscadorPanel.buscarIngredientes();
                }
            }
            fireEditingStopped();  // Detener la edición después de hacer clic
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.row = row;
            return button; // Mostrar el botón como componente de edición
        }

        @Override
        public Object getCellEditorValue() {
            return isIncrement ? "+" : "-"; // Retornar el símbolo adecuado
        }
    }

    // Método para agregar el panel secundario después de la creación
    private void insertarPanelBuscador() {
        this.buscadorPanel = new BuscadorIngredientesPanel();
        this.buscadorPanel.setVisible(true);
        
        panelBuscar.setLayout(new BorderLayout());
        panelBuscar.add(buscadorPanel, BorderLayout.CENTER);
        panelBuscar.revalidate();
        panelBuscar.repaint();
    }
    
    private void cargarListeners() {
        // Agregar el listener a la lista
        buscadorPanel.getlListaIngredientes().addListSelectionListener((ListSelectionEvent e) -> {
            // Habilitar el botón si hay un elemento seleccionado
            btnAgregar.setEnabled(!buscadorPanel.getlListaIngredientes().isSelectionEmpty());
        });
    }

    /**
     * Cargar los tipos de producto al combobox. Este método agrega los tipos de
     * productos obteniendolos directamente del enum. Agrega elemeto "No
     * seleccionado" como default.
     */
    public void cargarInformacion() {
        // Cargar los datos generales
        txtNombre.setText(productoElegido.getNombre());
        txtPrecio.setText(String.valueOf(productoElegido.getPrecio()));
        txtTipo.setText(productoElegido.getTipo().name());
        
        // Cargar los ingredientes
        for (ProductoIngredienteDTO productoIngrediente : productoElegido.getIngredientes()) {
            // Agregar el DTO a la lista
            this.ingredientes.add(productoIngrediente.getIngrediente());
            
            // Agregarlo a la tabla
            tableModel.addRow(new Object[]{productoIngrediente.getIngrediente().getNombre(), productoIngrediente.getIngrediente().getUnidadMedida(), "-", productoIngrediente.getCantidad(), "+"});
        }
    }

    /**
     * Método para agregar un ingrediente seleccionado. Agrega el ingrediente
     * seleccionado a la tabla de ingredientes. 
     */
    private void agregarIngredienteATabla() {
        String elementoSeleccionado = buscadorPanel.getlListaIngredientes().getSelectedValue();

        if (elementoSeleccionado == null || elementoSeleccionado.isEmpty()) {
            return;
        }
        
        String nombre = obtenerNombreIngrediente(elementoSeleccionado);
        String unidad = obtenerUnidadIngrediente(elementoSeleccionado);

        // Buscar el elemento en la tabla y actualizar
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (tableModel.getValueAt(i, 0).equals(nombre) && tableModel.getValueAt(i, 1).equals(unidad)) {
                return;
            }
        }
        
        if (agregarIngrediente(nombre, unidad)) {
            tableModel.addRow(new Object[]{nombre, unidad, "-", 1, "+"});
        }
    }
    
    private boolean agregarIngrediente(String nombre, String unidad) {
        try {
            ingredientes.add(coordinadorAplicacion.filtrarIngredientes(nombre, UnidadMedida.valueOf(unidad)).getFirst());
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar ingrediente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        return true;
    }
    
    private void quitarIngrediente(String nombre, String unidad) {
        try {
            ingredientes.remove(coordinadorAplicacion.filtrarIngredientes(nombre, UnidadMedida.valueOf(unidad)).getFirst());
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, "Error al quitar ingrediente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String obtenerNombreIngrediente(String elemento) {
        Pattern pattern = Pattern.compile("^(.*?)\\s*\\((.*?)\\)$");
        Matcher matcher = pattern.matcher(elemento);
        return matcher.matches() ? matcher.group(1) : "";
    }
    
    private String obtenerUnidadIngrediente(String elemento) {
        Pattern pattern = Pattern.compile("^(.*?)\\s*\\((.*?)\\)$");
        Matcher matcher = pattern.matcher(elemento);
        return matcher.matches() ? matcher.group(2) : "";
    }

    /**
     * Registra un nuevo producto. Este método registra un nuevo producto,
     * validandolo antes del proceso.
     *
     * @throws PresentacionException Si un dato ingresado no es válido o si hubo
     * un error al intentar el registro.
     */
    private void editarProducto() throws DatosInvalidosException, PresentacionException {
        try {
            validarCamposProducto();

            ProductoDTO productoEditado = new ProductoDTO(
                    txtNombre.getText(),
                    Double.valueOf(txtPrecio.getText()),
                    TipoProducto.valueOf(txtTipo.getText().toUpperCase())
            );

            List<ProductoIngredienteDTO> productosIngredientes = new ArrayList<>();

            for (int i = 0; i < tableModel.getRowCount(); i++) {
                ProductoIngredienteDTO productoIngrediente = new ProductoIngredienteDTO(
                        Integer.valueOf(tableModel.getValueAt(i, 3).toString()),
                        productoEditado,
                        ingredientes.get(i)
                );
                
                productosIngredientes.add(productoIngrediente);
            }
            
            productoEditado.setIngredientes(productosIngredientes);
            
            coordinadorAplicacion.actualizarProducto(productoEditado);
        } catch (PresentacionException e) {
            throw new PresentacionException(e.getMessage(), e);
        }
    }

    /**
     * Valida todos los campos ingresados del registro del producto.
     *
     * @throws PresentacionException Si algún campo ingresado no es válido (a
     * nivel presentación).
     */
    private void validarCamposProducto() throws DatosInvalidosException {
        Validaciones.validarNumero(txtPrecio.getText().trim(), "precio del producto");
        Validaciones.validarSeleccionTabla(tableModel, "ingrediente");
    }

    /**
     * Limpia todos los campos de los componentes.
     */
    private void limpiarCampos() {
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        this.txtTipo.setText("");
        this.buscadorPanel.getTxtNombreIngrediente().setText("");
        this.tableModel.setRowCount(0);
        
        this.ingredientes.clear();
    }

    /**
     * Inicia el proceso para registrar un producto. Implementa confirmaciones y
     * mensajes mediante cuadros de diálogo.
     */
    private void guardar() {
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea editar el producto?",
                "Confirmar registro", JOptionPane.YES_NO_OPTION);
        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            editarProducto();
            JOptionPane.showMessageDialog(this, "Producto editado con éxito.", "Registro confirmado", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, "Error al editar producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DatosInvalidosException e) {
            JOptionPane.showMessageDialog(this, "Error por datos no válidos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Verifica si hay campos con información ingresada.
     * @return True si encontró al menos un campo con información, false en caso contrario.
     */
    private boolean camposIngresados() {
        return !txtPrecio.getText().isBlank() || tableModel.getRowCount() != 0;
    }

    /**
     * Regresa al menú principal. Implementa confirmación para cancelar registro
     * si se detecta que hay información ingresada.
     */
    private void atras() {
        if (camposIngresados()) {
            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea cancelar la edición del producto?",
                    "Confirmar cancelación de registro", JOptionPane.YES_NO_OPTION);
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            JOptionPane.showMessageDialog(this, "No se editó el producto.", "Cancelación confirmada", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }
        
        this.dispose();
        coordinadorAplicacion.mostrarAdministrarProductosFrm();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbDatosGenerales;
    private javax.swing.JLabel lbNombreProducto;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbSeleccionarIngredientes;
    private javax.swing.JLabel lbTablaIngredientes;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scTablaIngredientes;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}