/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modulo_ingredientes;

import DTOs.IngredienteDTO;
import coordinadores.CoordinadorAplicacion;
import enums.UnidadMedida;
import exception.NegocioException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Filtro de búsqueda para ingredientes.
 * 
 * @author Ximena
 */
public class BuscadorIngredientesPanel extends javax.swing.JPanel {

    private CoordinadorAplicacion coordinador;
    
    private DefaultListModel<String> listModel; // Modelo para la lista
    private List<String> ingredientes; // PROVISIONAL
    
    /**
     * Creates new form BuscadorIngredientesPanel
     */
    public BuscadorIngredientesPanel() {
        initComponents();
        this.coordinador = CoordinadorAplicacion.getInstancia();
        
        this.listModel = new DefaultListModel<>();
        this.lListaIngredientes.setModel(listModel);
        
        cargarUnidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreIngrediente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbUnidadMedida = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lListaIngredientes = new javax.swing.JList<>();
        btnLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        txtNombreIngrediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreIngredienteKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Unidad de medida");

        cbUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUnidadMedidaActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lListaIngredientes);

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnLimpiar))
                    .addComponent(jLabel1)
                    .addComponent(cbUnidadMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreIngrediente)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreIngredienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreIngredienteKeyReleased
        buscarIngredientes();
    }//GEN-LAST:event_txtNombreIngredienteKeyReleased

    private void cbUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUnidadMedidaActionPerformed
        buscarIngredientes();
    }//GEN-LAST:event_cbUnidadMedidaActionPerformed

    private void cargarUnidades() {
        cbUnidadMedida.addItem("No seleccionado");
        
        for (UnidadMedida unidad : UnidadMedida.values()) {
            cbUnidadMedida.addItem(unidad.name());
        }
        
        cbUnidadMedida.setSelectedIndex(0);
    }
   
    private void buscarIngredientes() {
        String nombre = txtNombreIngrediente.getText().trim();
        UnidadMedida unidad = null;

        String selectedItem = cbUnidadMedida.getSelectedItem().toString();
        if (!selectedItem.equals("No seleccionado")) {
            unidad = UnidadMedida.valueOf(selectedItem);

        }

        try {
            List<IngredienteDTO> ingredientes = coordinador.filtrarIngredientes(nombre, unidad);
            actualizarListaIngredientes(ingredientes);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar ingredientes: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizarListaIngredientes(List<IngredienteDTO> ingredientesFiltrados) {
        listModel.clear();
        for (IngredienteDTO ing : ingredientesFiltrados) {
            listModel.addElement(ing.getNombre() + " (" + ing.getUnidadMedida() + ")");
        }
    }
    
    private void limpiar() {
        txtNombreIngrediente.setText("");
        cbUnidadMedida.setSelectedIndex(0);
        listModel.clear();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lListaIngredientes;
    private javax.swing.JTextField txtNombreIngrediente;
    // End of variables declaration//GEN-END:variables
}
