/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo_ingredientes;

import DTOs.IngredienteDTO;
import coordinadores.CoordinadorAplicacion;
import enums.UnidadMedida;
import excepciones.PresentacionException;
import exception.NegocioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validaciones.Validaciones;

/**
 *
 * @author Ximena
 */
public class RegistrarIngredienteFrm extends javax.swing.JFrame {

    private CoordinadorAplicacion coordinadorAplicacion;
    
    /**
     * Creates new form RegistrarIngredienteFrm
     */
    public RegistrarIngredienteFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.coordinadorAplicacion = CoordinadorAplicacion.getInstancia();
        cargarUnidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lNombreIngrediente = new javax.swing.JLabel();
        lUnidadMedida = new javax.swing.JLabel();
        lCantidadStock = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbUnidadMedida = new javax.swing.JComboBox<>();
        txtCantidadStock = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTitulo.setText("Registrar Ingrediente");

        lNombreIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lNombreIngrediente.setText("Nombre");

        lUnidadMedida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lUnidadMedida.setText("Unidad de medida");

        lCantidadStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lCantidadStock.setText("Cantidad en stock");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        cbUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUnidadMedidaActionPerformed(evt);
            }
        });

        txtCantidadStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadStockActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTitulo)
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNombreIngrediente)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUnidadMedida)
                            .addComponent(cbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCantidadStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidadStock))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lTitulo)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUnidadMedida)
                    .addComponent(lCantidadStock)
                    .addComponent(lNombreIngrediente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUnidadMedidaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCantidadStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadStockActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            guardar();
        } catch (PresentacionException ex) {
            Logger.getLogger(RegistrarIngredienteFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        atras();
    }//GEN-LAST:event_btnAtrasActionPerformed
    
    /**
     * Cargar las unidades de medida de los ingredientes a un combo box. Agrega
     * las unidades de medida obteniéndolas del enum.
     */
    private void cargarUnidades() {
        cbUnidadMedida.addItem("No seleccionado");
        
        for (UnidadMedida unidad : UnidadMedida.values()) {
            cbUnidadMedida.addItem(unidad.name());
        }
        
        cbUnidadMedida.setSelectedIndex(0);
    }
    
    /**
     * Validar que se ingresaron campos. Valida si se han ingresado datos en los
     * campos de ingredientes, validando directamente de la clase Validaciones.
     * @throws PresentacionException 
     */
    private void validarCamposIngrediente() throws PresentacionException {
        Validaciones.validarTexto(txtNombre.getText().trim(), "nombre");
        Validaciones.validarCombobox(cbUnidadMedida, "unidad de medida");
        Validaciones.validarNumero(txtCantidadStock.getText().trim(), "cantidad en stock");
    }
    
    
    /**
     * Limpiar campos de texto y combo box. Limpia los campos de texto y el 
     * combo box después de registrar un nuevo ingrediente.
     */
    private void limpiarCampos() {
        this.txtNombre.setText("");
        this.cbUnidadMedida.setSelectedIndex(0);
        this.txtCantidadStock.setText("");
    }   
    
    /**
     * Guardar registro de ingrediente. Método para el botón de "Guardar", que
     * muestra un mensaje de confirmación antes de guardar el nuevo ingrediente.
     */
    private void guardar() throws PresentacionException {
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea registrar el ingrediente?", "Confirmar registro",
                JOptionPane.YES_NO_OPTION);
        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Generar DTO del ingrediente
        try {
            validarCamposIngrediente();
            
            String nombre = txtNombre.getText().trim();
            UnidadMedida unidad = UnidadMedida.valueOf(cbUnidadMedida.getSelectedItem().toString());
            int cantidadStock = Integer.parseInt(txtCantidadStock.getText().trim());
            
            // Crear DTO
            IngredienteDTO ingredienteDTO = new IngredienteDTO(nombre, unidad, cantidadStock);
            // Enviar a negocio
            IngredienteDTO ingredienteRegistrado = coordinadorAplicacion.registrarIngrediente(ingredienteDTO);
            
            // Mostrar mensaje de éxito y limpiar campos
            JOptionPane.showMessageDialog(this, "Ingrediente registrado con éxito: " + ingredienteRegistrado.getNombre(),
                    "Registro confirmado", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error en registro", JOptionPane.ERROR_MESSAGE);
        }
 
    }
    
    /**
     * Validar si se ingresaron campos en el registro.
     * @return True si se encontró algún campo ingresadp, false en caso contrario.
     */
    private boolean camposIngresados() {
        return !txtNombre.getText().isBlank() || cbUnidadMedida.getSelectedIndex() != 0 || !txtCantidadStock.getText().isBlank();
    }
    
    /**
     * Regresar al menú principal. Implementa confirmación para cancelar registro
     * si se detecta que hay información ingresada.
     */
    private void atras() {
        if (camposIngresados()) {
            int opcion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea cancelar el registro del ingrediente?",
                "Confirmar cancelación de registro", JOptionPane.YES_NO_OPTION);
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }
            
            JOptionPane.showMessageDialog(this, "No se registró el ingrediente", "Cancelación confirmada", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }
        
        this.dispose();
        coordinadorAplicacion.mostrarAdministrarIngredientes();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbUnidadMedida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCantidadStock;
    private javax.swing.JLabel lNombreIngrediente;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUnidadMedida;
    private javax.swing.JTextField txtCantidadStock;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}