/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo_clientes;

import DTOs.ClienteDTO;
import coordinadores.CoordinadorAplicacion;
import excepciones.PresentacionException;
import exception.NegocioException;
import javax.swing.JOptionPane;
import validaciones.Validaciones;

/**
 *
 * @author dario
 */
public class RegistrarClientes extends javax.swing.JFrame {
     private CoordinadorAplicacion coordinador;

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarClientes() {
        initComponents();
       this.coordinador = CoordinadorAplicacion.getInstancia();
        setLocationRelativeTo(null);
    }
    
    private void configurarValidaciones(){
         FieldTelefono.setToolTipText("10 dígitos sin guiones ni espacios");
         FieldCorreo.setToolTipText("ejemplo@dominio.com");
          FieldTelefono.setDocument(new javax.swing.text.PlainDocument() {
            @Override
            public void insertString(int offs, String str, javax.swing.text.AttributeSet a) 
                throws javax.swing.text.BadLocationException {
                if (str == null) return;
                String newStr = str.replaceAll("[^0-9]", "");
                super.insertString(offs, newStr, a);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RadioClienteF = new javax.swing.JRadioButton();
        txtnombre = new javax.swing.JLabel();
        Fieldnombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JLabel();
        FieldApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JLabel();
        FieldApellidoM = new javax.swing.JTextField();
        txtCorrreo = new javax.swing.JLabel();
        FieldCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JLabel();
        FieldTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Registro Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Formulario de registro");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Tipo de cliente a registrar ");

        jLabel4.setText("Seleccione el tipo de cliente:");

        RadioClienteF.setText("Cliente Frecuente");
        RadioClienteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioClienteFActionPerformed(evt);
            }
        });

        txtnombre.setText("Nombre*");

        txtApellidoP.setText("Apellido Paterno*");

        FieldApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldApellidoPActionPerformed(evt);
            }
        });

        txtApellidoM.setText("Apellido Materno");

        txtCorrreo.setText("Correo");

        txtTelefono.setText("Telefono*");

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("* Son campos obligatorios");

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtCorreoLayout = new javax.swing.GroupLayout(txtCorreo);
        txtCorreo.setLayout(txtCorreoLayout);
        txtCorreoLayout.setHorizontalGroup(
            txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtCorreoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtCorreoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtCorreoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(20, 20, 20))))
            .addGroup(txtCorreoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(RadioClienteF)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombre)
                    .addComponent(Fieldnombre)
                    .addComponent(txtApellidoP)
                    .addComponent(FieldApellidoP)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldApellidoM)
                    .addComponent(FieldCorreo)
                    .addComponent(txtTelefono)
                    .addComponent(FieldTelefono)
                    .addComponent(txtCorrreo))
                .addGap(101, 101, 101))
            .addGroup(txtCorreoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(105, 105, 105))
        );
        txtCorreoLayout.setVerticalGroup(
            txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCorreoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre))
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtCorreoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(RadioClienteF))
                    .addGroup(txtCorreoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorrreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioClienteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioClienteFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioClienteFActionPerformed

    private void FieldApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldApellidoPActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:                                            
        try {
            validarCampos();  // Esta llamada ya usa los Field correctos

            ClienteDTO clienteDTO = new ClienteDTO();
            clienteDTO.setNombre(Fieldnombre.getText().trim());  // Corregido: Fieldnombre en lugar de txtnombre
            clienteDTO.setApellidoPaterno(FieldApellidoP.getText().trim());  // FieldApellidoP
            clienteDTO.setApellidoMaterno(FieldApellidoM.getText().trim());  // FieldApellidoM
            clienteDTO.setTelefono(FieldTelefono.getText().trim());  // FieldTelefono
            clienteDTO.setCorreo(FieldCorreo.getText().trim());  // FieldCorreo
            clienteDTO.setTipo(RadioClienteF.isSelected() ? "Frecuente" : null);

            int confirmacion = JOptionPane.showConfirmDialog(
                this, 
                "¿Desea registrar este cliente?", 
                "Confirmar registro", 
                JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                ClienteDTO clienteRegistrado = coordinador.registrarClientes(clienteDTO);
                JOptionPane.showMessageDialog(
                    this, 
                    "Cliente registrado exitosamente", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }
        } catch (PresentacionException | NegocioException e) {
            JOptionPane.showMessageDialog(
                this, 
                e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void validarCampos() throws PresentacionException {
        Validaciones.validarTexto(Fieldnombre.getText().trim(), "nombre");  
        Validaciones.validarTexto(FieldApellidoP.getText().trim(), "apellido paterno");  
        Validaciones.validarTelefono(FieldTelefono.getText().trim()); 

        if (!FieldCorreo.getText().trim().isEmpty()) {  
            Validaciones.validarEmail(FieldCorreo.getText().trim());
        }
    }
    
    private void limpiarCampos() {
    Fieldnombre.setText("");
    FieldApellidoP.setText("");
    FieldApellidoM.setText("");
    FieldTelefono.setText("");
    FieldCorreo.setText("");
    RadioClienteF.setSelected(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here                          
        int confirmacion = JOptionPane.showConfirmDialog(
            this, 
            "¿Desea cancelar el registro? Los datos no guardados se perderán.", 
            "Confirmar cancelación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE  
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            return; // Si el usuario elige "No", no hacer nada.
        }

        // Limpiar los campos antes de cerrar el formulario.
        limpiarCampos();

        this.dispose(); // Cierra la ventana.
        coordinador.mostrarMenu(); // Regresa al menú principal.

        
    }//GEN-LAST:event_btnCancelarActionPerformed
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldApellidoM;
    private javax.swing.JTextField FieldApellidoP;
    private javax.swing.JTextField FieldCorreo;
    private javax.swing.JTextField FieldTelefono;
    private javax.swing.JTextField Fieldnombre;
    private javax.swing.JRadioButton RadioClienteF;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtApellidoM;
    private javax.swing.JLabel txtApellidoP;
    private javax.swing.JPanel txtCorreo;
    private javax.swing.JLabel txtCorrreo;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtnombre;
    // End of variables declaration//GEN-END:variables
}
